# Generated by Django 4.2 on 2024-11-27 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название категории', max_length=200, verbose_name='Категория курса')),
            ],
        ),
        migrations.CreateModel(
            name='DurationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(help_text='Введите длительность курса', verbose_name='Длительность курса')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя преподавателя', max_length=100, verbose_name='Имя преподавателя')),
                ('middle_name', models.CharField(help_text='Введите фамилию преподавателя', max_length=100, verbose_name='Фамилия преподавателя')),
                ('last_name', models.CharField(help_text='Введите отчество преподавателя', max_length=100, verbose_name='Отчество преподавателя')),
                ('specialization', models.CharField(help_text='Введите специальность преподавателя', max_length=200, verbose_name='Специальность преподавателя')),
                ('description', models.TextField(help_text='Введите проекты и языки программирования, которые знает преподаватель', verbose_name='Описание карьеры')),
                ('experience', models.IntegerField(help_text='Введите стаж работы преподавателя в IT-сфере', verbose_name='Стаж работы')),
                ('photo', models.ImageField(blank=True, help_text='Введите фото преподавателя', null=True, upload_to='images', verbose_name='Фото преподавателя')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя студента', max_length=100, verbose_name='Имя студента')),
                ('middle_name', models.CharField(help_text='Введите фамилию студента', max_length=100, verbose_name='Фамилия студента')),
                ('last_name', models.CharField(help_text='Введите отчество студента', max_length=100, verbose_name='Отчество студента')),
                ('completion_date', models.DateField(blank=True, help_text='Введите дату окончания прохождения курса', null=True, verbose_name='Дата окончания прохождения курса')),
                ('datereg', models.DateField(blank=True, help_text='Введите дату регистрации на сайт', null=True, verbose_name='Дата регистрации на сайт')),
                ('statusych', models.ForeignKey(help_text='Введите статус прохождения курса', on_delete=django.db.models.deletion.CASCADE, to='zxc.status', verbose_name='Статус прохождения курса')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название курса', max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(help_text='Введите описание курса', verbose_name='Описание курса')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость курса', max_digits=7, verbose_name='Стоимость курса')),
                ('categorycourse', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='zxc.category', verbose_name='Категория курса')),
                ('duration', models.ForeignKey(help_text='Введите длительность курса', on_delete=django.db.models.deletion.CASCADE, to='zxc.durationcourse', verbose_name='Длительность курса')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Введите описание категории', verbose_name='Описание категории')),
                ('complexity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='Введите сложность категории', verbose_name='Сложность курса')),
                ('languageprog', models.CharField(help_text='Введите основной язык программирования', max_length=30, verbose_name='Основной язык программирования')),
                ('title', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='zxc.category', verbose_name='Категория курса')),
            ],
        ),
    ]
