# Generated by Django 4.2 on 2025-03-25 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Выберите студентов, записанных на этот курс', related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
