# Generated by Django 4.2 on 2024-11-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydetail',
            old_name='title',
            new_name='titles',
        ),
    ]
