# Generated by Django 4.2 on 2025-03-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0002_remove_course_student_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(help_text='Введите обложку курса', null=True, upload_to='course_photos/', verbose_name='Обложка курса'),
        ),
    ]
