# Generated by Django 4.2 on 2024-11-27 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0003_rename_title_course_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydetail',
            old_name='titles',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='titles',
            new_name='title',
        ),
    ]
