# Generated by Django 4.2 on 2025-03-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0004_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите стоимость курса', max_digits=7, null=True, verbose_name='Стоимость курса'),
        ),
    ]
