# Generated by Django 4.2 on 2024-11-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0006_user_status_alter_user_statusych_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
