# Generated by Django 4.2 on 2024-11-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0007_remove_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(default=1, help_text='Выберите курс', on_delete=django.db.models.deletion.CASCADE, to='zxc.course', verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
