# Generated by Django 4.2 on 2024-11-27 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0008_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Выберите курс', null=True, on_delete=django.db.models.deletion.CASCADE, to='zxc.course', verbose_name='Курс'),
        ),
    ]
