# Generated by Django 4.2 on 2024-11-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0009_alter_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ForeignKey(default=1, help_text='Выберите преподавателя для курса', on_delete=django.db.models.deletion.CASCADE, to='zxc.teacher', verbose_name='Преподаватель курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(help_text='Выберите курс', null=True, on_delete=django.db.models.deletion.CASCADE, to='zxc.course', verbose_name='Курс'),
        ),
    ]
