# Generated by Django 4.2 on 2024-11-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0010_course_teachers_alter_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, help_text='Введите обложку курса', null=True, upload_to='images', verbose_name='Обложка курса'),
        ),
    ]
