# Generated by Django 4.2 on 2024-11-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0011_course_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(default=1, help_text='Введите обложку курса', upload_to='images', verbose_name='Обложка курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Выберите курс', null=True, on_delete=django.db.models.deletion.CASCADE, to='zxc.course', verbose_name='Курс'),
        ),
    ]
