# Generated by Django 4.2 on 2024-11-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0012_alter_course_photo_alter_user_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(help_text='Выберите преподавателя (преподавателей) для курса', to='zxc.teacher', verbose_name='Преподаватель (преподаватели) курса'),
        ),
    ]
