# Generated by Django 4.2 on 2024-12-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0016_remove_categorydetail_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categorycourse',
            field=models.CharField(choices=[('programming', 'Программирование'), ('english', 'Английский язык'), ('game', 'Игры'), ('music_and_cinema', 'Кино и музыка')], default='programming', max_length=50),
        ),
    ]
