# Generated by Django 4.2 on 2024-12-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0017_alter_course_categorycourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(help_text='Введите обложку курса', upload_to='course_photos/', verbose_name='Обложка курса'),
        ),
    ]
