# Generated by Django 4.2 on 2025-02-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxc', '0019_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Выберите студента курса', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='zxc.user', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Выберите курс', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='zxc.course', verbose_name='Курс'),
        ),
    ]
